### ISSUE TITLE
Newsfeed counters are not decremented when activity is read

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#84]
`POST /api/activities/read/` is not fired when entering activity detail, or fails with `POST https://api-dev.powerli.ne/api/activities/read/ 500 (Internal Server Error)`

**Comment by jterps08** [comment]
The newsfeed counters should count the following:

**Priority Zone Content**
- Unread petitions and unread discussions
- Unanswered polls, events, fundraisers/crowdfunders
- Unanswered _boosted_ posts (micropetitions)

All non-boosted posts (micropetitions) and any "read" or "answered" items above are considered Non-Priority Zone. The backend should provide Priority Zone activity items first before Non-Priority Zone items.

**Comment by petervojtek** [comment]
current behaviour is following:

The newsfeed counter numbers are computed on frontend via following business logic for given group:
 when activity item has`NOT answered && NOT closed && NOT ignore_count`, then increase the group's newsfeed counter by 1.

It does not seem to take into account whether a post/petition is boosted or not at all (actually I have not met the words `boost/boosted` anywhere in frontend source code, nor in API doc).
It does not seem to take into account  `Unread petitions and unread discussions` at all.
It does not seem to take into accout Priority/non Priority zone.

@jterps08 , Regarding Priority zone in general -- I am not sure how I am supposed to determine whether an activity item is in Priority zone or not. Currently there is this [messy business logic](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity/activity-model.js#L84) to resolve if an actity item is in priority zone, but I am in doubt whether it corresponds to your mental model :) and actually it is not used to compute newsfeed counters.

Maybe I do not need to write code for the priority zone detection business logic on frontend at all, because
given that `The backend should provide Priority Zone activity items first before Non-Priority Zone items.`, it means that backend business logic is already aware of priority zones. One approach would be that an activity item will be given an attribute e.g. `isInPriorityZone: true/false` and I will just blindly trust it.

**Comment by jterps08** [comment]
Few thoughts:
1) Boosted = Publish_status on the micropetition (https://github.com/PowerlineApp/powerline-server/wiki/Micropetition)
2) I think @igaponov may need to clarify what the backend is doing exactly in this PR (https://github.com/PowerlineApp/powerline-server/pull/113)
3) The way we need the app to work is described in https://github.com/PowerlineApp/powerline-server/issues/58... I believe PR 113 on the server addressed 58 in full, but I don't know how it impacts the frontend. 
4) There was a time when unread petitions, unread discussions, and boosted micropetitions were included in the count. There has never been a formal flag indicating priority zone or not.

The objective is the following:

**Prioritized Zone, listed chronologically**
- All unread Petitions, unread Discussions, unanswered polls, unanswered fundraisers, unanswered events, unanswered boosted posts that are not expired
- Note: Counters/badges reflect the number of items that fall within this zone. Notification alerts are sent for everything in this zone.

**Non-Prioritized Zone, listed chronologically beginning _after _the oldest priority item**
- All Non-Boosted User Posts and Petitions that are not expired
- All previously-prioritized content that has been read (Petition/Discussion) or answered (Poll/Event/Fundraiser/Boosted Post) - the flag needs to be switched from true to false once the user has read the petition, read the discussion, answered the poll/fundraiser/event, or answered a boosted post. The mobile app will tell the server when a petition or discussion has been read. The server will automatically update the flag when a poll/fundraiser/event has been answered or a boosted post has been answered.
- Note: Non-boosted user posts are always treated chronologically with no special prioritization. Boosted user posts are prioritized like leader's posts.

**Expired Zone, listed chronologically beginning after the oldest non-expired, non-priority zone item.**
- All other activities that do not fit into the above two categories.

We moved this from being handled entirely on the frontend to being at least partially handled on the backend so that we could 1) support infinite scrolling / pagination without screwing up the sort order of the feed (first ten items, next ten items, etc.), and 2) so that once an activity was read/answered on mobile, it was effectively read/answered on web, too...

**Comment by igaponov** [comment]
@jterps08 in that PR activities were sorted on backend, no need to sort it on frontend now.

@petervojtek each activity now has boolean attribute `read`

**Comment by petervojtek** [comment]
blocked by #130

**Comment by petervojtek** [comment]
I split this issue into several smaller other issue, see references. This issue deals only with the original bug in title: "Newsfeed counters are not decremented when activity is read"

**Comment by petervojtek** [comment]
@igaponov , I am confused by following backend API behaviour - I am not sure if I am using API in a wrong way or not:

 I experience following behaviour:
1. GET list of activites, activity.entity.id=176 has `read=false`
2. PATCH for activity.entity.id=176 with `read=true`
3. then I again GET list of activites, but the activity=176 still has `read=false` while I expect it to provide `read=true`

Details of step 2:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:200 OK

Content-Type:application/json

request body:
{"activities":[{"id":176,"read":true}]}
```

Details for step 3:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"id":405,"title":"","description":"test sorting out of priority zone","sent_at":"Tue, 05 Jul 2016 09:11:33 +0000","expire_at":"Wed, 06 Jul 2016 09:11:33 +0000","responses_count":0,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":180,"group_id":286},"read":false,"updated_at":"2016-07-05T09:11:33+0000","quorum":0},{"id":402,"title":"","description":"Micropetition to work 20 hours a week only.","sent_at":"Fri, 01 Jul 2016 06:51:52 +0000","expire_at":"Sat, 02 Jul 2016 06:51:52 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":178,"group_id":6},"read":true,"updated_at":"2016-07-01T06:51:52+0000","quorum":1},{"id":401,"title":"Petition to save coal power plants","description":"Whatever","sent_at":"Fri, 01 Jul 2016 06:42:22 +0000","expire_at":"Sat, 02 Jul 2016 06:42:22 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":177,"group_id":6},"read":true,"updated_at":"2016-07-01T06:42:22+0000","quorum":1},{"id":400,"title":"Save the world","description":"again","sent_at":"Fri, 01 Jul 2016 06:34:53 +0000","expire_at":"Sat, 02 Jul 2016 06:34:53 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":176,"group_id":285},"read":false,"updated_at":"2016-07-01T06:34:53+0000","quorum":0},{"id":399,"title":"","description":"Whatever","sent_at":"Thu, 30 Jun 2016 10:19:52 +0000","expire_at":"Fri, 01 Jul 2016 10:19:52 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":175,"group_id":285},"read":false,"updated_at":"2016-06-30T10:19:52+0000","quorum":0},{"id":398,"title":"","description":"test 44","sent_at":"Thu, 30 Jun 2016 08:15:03 +0000","expire_at":"Fri, 01 Jul 2016 08:15:03 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":174,"group_id":1},"read":false,"updated_at":"2016-06-30T08:15:03+0000","quorum":6},{"id":397,"title":"","description":"Test follow & ignore 2","sent_at":"Thu, 30 Jun 2016 08:10:37 +0000","expire_at":"Fri, 01 Jul 2016 08:10:37 +0000","responses_count":0,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":173,"group_id":285},"read":false,"updated_at":"2016-06-30T08:10:37+0000","quorum":0},{"id":396,"title":"","description":"test follow & ignore","sent_at":"Thu, 30 Jun 2016 08:07:49 +0000","expire_at":"Fri, 01 Jul 2016 08:07:49 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":172,"group_id":285},"read":false,"updated_at":"2016-06-30T08:07:49+0000","quorum":0},{"id":391,"title":"","description":"Peter10's Post to USA group","sent_at":"Wed, 29 Jun 2016 14:35:45 +0000","expire_at":"Thu, 30 Jun 2016 14:35:45 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":170,"group_id":1},"read":false,"updated_at":"2016-06-29T14:35:45+0000","quorum":6},{"id":389,"title":"","description":"California post #3 by Peter8","sent_at":"Wed, 29 Jun 2016 08:04:41 +0000","expire_at":"Thu, 30 Jun 2016 08:04:41 +0000","responses_count":0,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":168,"group_id":6},"read":false,"updated_at":"2016-06-29T08:04:41+0000","quorum":0},{"id":388,"title":"","description":"California post #2 by peter8","sent_at":"Wed, 29 Jun 2016 08:01:41 +0000","expire_at":"Thu, 30 Jun 2016 08:01:41 +0000","responses_count":0,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":167,"group_id":6},"read":false,"updated_at":"2016-06-29T08:01:41+0000","quorum":0},{"id":387,"title":"","description":"California Post #1 by Peter7","sent_at":"Wed, 29 Jun 2016 07:58:31 +0000","expire_at":"Thu, 30 Jun 2016 07:58:31 +0000","responses_count":0,"owner":{"id":69,"type":"user","official_title":"","first_name":"Peter7","last_name":"Peter7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":166,"group_id":6},"read":false,"updated_at":"2016-06-29T07:58:31+0000","quorum":0},{"id":373,"title":"","description":"test bug 74 3rd attemtp","sent_at":"Thu, 23 Jun 2016 05:51:56 +0000","expire_at":"Fri, 24 Jun 2016 05:51:56 +0000","responses_count":0,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/576b9b633f3fa.jpeg"},"entity":{"type":"micro-petition","id":153,"group_id":1},"read":true,"updated_at":"2016-06-23T05:51:56+0000","quorum":5},{"id":354,"title":"","description":"Test bug #74","sent_at":"Wed, 22 Jun 2016 07:26:42 +0000","expire_at":"Thu, 23 Jun 2016 07:26:42 +0000","responses_count":0,"owner":{"id":16,"type":"user","official_title":"","first_name":"Jesse","last_name":"Chen","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/5630c377e06b3.jpeg"},"entity":{"type":"micro-petition","id":149,"group_id":1},"read":true,"updated_at":"2016-06-22T07:26:42+0000","quorum":5},{"id":404,"title":"","description":"San Diego Post to rename Pacific ocean","sent_at":"Mon, 04 Jul 2016 12:30:28 +0000","expire_at":"Tue, 05 Jul 2016 12:30:12 +0000","responses_count":1,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":179,"group_id":285},"read":true,"updated_at":"2016-07-04T12:30:28+0000","quorum":0},{"id":403,"title":"","description":"San Diego Post to rename Pacific ocean","sent_at":"Mon, 04 Jul 2016 12:30:12 +0000","expire_at":"Tue, 05 Jul 2016 12:30:12 +0000","responses_count":1,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":179,"group_id":285},"read":true,"updated_at":"2016-07-04T12:30:12+0000","quorum":0},{"id":395,"title":"","description":"California post #4 by Peter8","sent_at":"Thu, 30 Jun 2016 06:19:04 +0000","expire_at":"Thu, 30 Jun 2016 08:11:34 +0000","responses_count":1,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":169,"group_id":6},"read":false,"updated_at":"2016-06-30T06:19:04+0000","quorum":0},{"id":390,"title":"","description":"California post #4 by Peter8","sent_at":"Wed, 29 Jun 2016 08:11:34 +0000","expire_at":"Thu, 30 Jun 2016 08:11:34 +0000","responses_count":1,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":169,"group_id":6},"read":false,"updated_at":"2016-06-29T08:11:34+0000","quorum":0}],"totalItems":20}
```

I am actually not sure if I use the proper ID as a reference -- I use `activity.entity.id` (id=176). Out of curiousity I also tried to use `activity.id` (id=400) but behaviour was the same.

**Comment by igaponov** [comment]
@petervojtek you should use `activity.id`. There is an error with query to retrieve activities to mark as read, it's fixed in https://github.com/PowerlineApp/powerline-server/pull/169

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#169 merged. just needs to be deployed.

**Comment by igaponov** [comment]
deployed

**Comment by petervojtek** [comment]
@igaponov , thanks, I adopted the acivity.id.  

Currently the PATCH read request fails with error 500:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:500 Internal Server Error

{"activities":[{"id":406,"read":true}]}

```

 Despite the error 500, the read=true is however is set properly, as the subsequent `GET activities` properly provides `read=true` for activity 406.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/170

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#170 deployed

**Comment by petervojtek** [comment]
@igaponov , I still experience the error, this time with different error detail:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing 'INSERT INTO activities_read (created_at, activity_id, user_id) VALUES (?, ?, ?)' with params [\"2016-07-07 05:07:09\", 406, 73]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '406-73' for key 'UNIQ_1DFA339A81C06096A76ED395'"}
```

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/173

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#173 was merged. however, just not sure if it was deployed. ran out of time this morning. @igaponov can you check when you get a few seconds? thanks.

**Comment by jterps08** [comment]
I was just logging in to do it myself - looks like Igor is already on top of it and trying to deploy now...

**Comment by igaponov** [comment]
deployed

**Comment by petervojtek** [comment]
@igaponov, I still experience the error :(

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing 'INSERT INTO activities_read (created_at, activity_id, user_id) VALUES (?, ?, ?)' with params [\"2016-07-10 06:29:58\", 412, 73]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '412-73' for key 'UNIQ_1DFA339A81C06096A76ED395'"}
```

**Comment by jterps08** [comment]
FYI @igaponov is out of office from July 9-16

**Comment by petervojtek** [comment]
ok, maybe @austinpapp may help us :)

**Comment by igaponov** [comment]
@jterps08 sometimes I can answer questions.

this issue should be fixed after https://github.com/PowerlineApp/powerline-server/pull/173 is deployed

**Comment by jterps08** [comment]
Thanksss Igor! :-)

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#173 was deployed.

**Comment by petervojtek** [comment]
I still experience the error:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:500 Internal Server Error

{"activities":[{"id":440,"read":true}]}

{"code":500,"message":"An exception occurred while executing 'INSERT INTO activities_read (created_at, activity_id, user_id) VALUES (?, ?, ?)' with params [\"2016-07-16 11:30:06\", 440, 73]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '440-73' for key 'UNIQ_1DFA339A81C06096A76ED395'"}
```

I am not sure if you have some unit test suite, but this use case seems to be easily unit-testable..  I prefer to be a developer and not a tester :(

**Comment by igaponov** [comment]
@petervojtek of course I added test for this case before.

User - Peter10

```
http PATCH https://api-dev.powerli.ne/api/v2/activities "Token: $TOKEN" activities:='[{"id":440,"read":true}]'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, Authorization, content-type, Token
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Sat, 16 Jul 2016 12:04:23 GMT
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: PHPSESSID=shsescd3q3b861bosci8d2g3m2; path=/
Transfer-Encoding: chunked
X-Debug-Token: 77a374

[
    {
        "description": "Petition 22", 
        "entity": {
            "group_id": 1, 
            "id": 213, 
            "type": "micro-petition"
        }, 
        "expire_at": "Fri, 15 Jul 2016 05:51:06 +0000", 
        "id": 440, 
        "owner": {
            "avatar_file_path": "https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png", 
            "first_name": "Peter9", 
            "id": 71, 
            "last_name": "Peter9", 
            "official_title": "", 
            "type": "user"
        }, 
        "quorum": 6, 
        "read": true, 
        "responses_count": 0, 
        "sent_at": "Thu, 14 Jul 2016 05:51:06 +0000", 
        "title": "Petition 22", 
        "updated_at": "2016-07-14T05:51:06+0000"
    }
]
```

**Comment by petervojtek** [comment]
I don't know what should I do then. I still experience the backend bug.

**Comment by igaponov** [comment]
@petervojtek I don't see the error in logs on dev server. Are you sure you didn't change your `hosts` file and you call real api-dev.powerli.ne?

**Comment by petervojtek** [comment]
@igaponov , I believe I use `api-dev.powerli.ne` which translates to `52.5.45.80:443`.

Now it seems to work properly for some activities:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:200 OK
Remote Address:52.5.45.80:443

{"activities":[{"id":438,"read":true}]}
```

There are still some activities which fail:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities
Request Method:PATCH
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443

{"activities":[{"id":430,"read":true}]}


{"code":500,"message":"An exception occurred while executing 'INSERT INTO activities_read (created_at, activity_id, user_id) VALUES (?, ?, ?)' with params [\"2016-07-17 13:31:56\", 430, 73]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '430-73' for key 'UNIQ_1DFA339A81C06096A76ED395'"}
```

However it seems to be only issue of those activities in which there was attempt to mark them as read in the past when the backend had the bug (and are marked as `read=false` in get list of activities). Visiting them fails with the error, but then they seem to _recover_ on the backend, and subsequent GET list of activities assigns them read=true. I consider this bug as fixed from mobile app point of view.
